### ISSUE TITLE
添加多个nacos连接, 展示的还是第一个nacos的数据

### ISSUE THREAD

**Issue by anaer** [noir-lattice/nacos-vsc-addon#2]
![rGcNY8.png](https://s3.ax1x.com/2020/12/17/rGcNY8.png)
![](https://s3.ax1x.com/2020/12/17/rGgYu9.png)
![](https://s3.ax1x.com/2020/12/17/rGgw4K.png)

**Comment by noir-lattice** [comment]
多连接如果url相同是覆盖原有配置，如果不是这个场景麻烦提供一下操作过程 暂时没复现
